### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Itmedesu** [KevCui/animepahe-dl#49]
Downloaded anime audio and video not matching....they are not syncing

**Comment by KevCui** [comment]
Hi @Itmedesu, a similar issue was reported in #48. It's been solved by the reporter `I just updated some parts of my program and the problem was solved....` https://github.com/KevCui/animepahe-dl/issues/48#issuecomment-1051385644 Maybe try first to update some programs on your machine and check again?

If you still cannot solve the problem, please run the script with `-d` flag to enable debug mode, and paste some logs here, I may take a look.

**Comment by Itmedesu** [comment]
Not working.....
My program is up-to-date
![Screenshot_2022-03-03-18-06-19-12_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/100840612/156566488-43e7b023-846b-4446-93fe-8236fd349d96.png)

**Comment by Itmedesu** [comment]
Hey man can I increase the downloading speed of program if I modify the script....??

**Comment by KevCui** [comment]
Hi @Itmedesu, from your log, it looks like the download is not finished. I can see your speed is really slow. If it's not caused by your network, it may be the throttling from the server side. Unfortunately, I cannot do much about this since I don't have any controls. Feel free to modify the script if you are able to increase your download speed.

**Comment by Itmedesu** [comment]
Ok but what about the lagging problem...

**Comment by KevCui** [comment]
@Itmedesu I assume it's also caused by the incomplete download.

**Comment by Itmedesu** [comment]
I reinstalled the program 
It started working....
But when I put it in my TV the same problem happens....

**Comment by KevCui** [comment]
@Itmedesu If the downloaded media has no issue on your machine, but it has the issue on your TV,  it sounds like a media player problem. I don't know what codecs are used on your TV... By the way, did you check with other popular/common media players on your TV, like VLC?

**Comment by Itmedesu** [comment]
It starts working perfectly for a minute and after that the same problem occurs

**Comment by Itmedesu** [comment]
The issue has been solved bro
I don't know what happened 
But it started working fine In my TV....

**Comment by Itmedesu** [comment]
Last question...
What is debug mode
Can we speed up the downloading speed in debug mode....

**Comment by KevCui** [comment]
Hey @Itmedesu, I'm glad to hear that it works. The debug mode won't increase download speed, it only prints debug logs in the terminal.
