### ISSUE TITLE
date: invalid date

### ISSUE THREAD

**Issue by testbughub** [KevCui/animepahe-dl#54]
Hi!

First off, thank you for this script. It has really come in handy.

Now to my issue.

Every time I'm using the script, I get this error:
```
$ ./animepahe-dl.sh -a 'Shingeki no Kyojin'
date: invalid date ‘sön  3 apr 2022 20:23:22 CEST +10080 minutes’
[INFO] Wait a few seconds for fetching cookie...
date: invalid date ‘mån  4 apr 2022 10:02:20 CEST +10080 minutes’
[INFO] Wait a few seconds for fetching cookie...
date: invalid date ‘mån  4 apr 2022 10:02:20 CEST +10080 minutes’
```
And it repeats a couple of times.
It can take a few minutes/tries, but it still works eventually.

My first thought is that it could be because I have set up my machine to  
use English language but the rest with Swedish (time & currency etc),  
but I thought I'd ask anyway.

Cheers!

**Comment by KevCui** [comment]
Hey @testbughub, if I understand correctly, the problem you are facing:

> And it repeats a couple of times. It can take a few minutes/tries, but it still works eventually.

It might be caused by the user agent, not related to date command. In the latest commit, I added some working user agents. It may help to solve this problem.

Please try to pull the latest commit and try again. Tell me it works :)

**Comment by testbughub** [comment]
I thought I had updated everything, but apparently I hadn't, so now it works just fine without any errors. My bad!
Thank you again, and thanks for the quick reply!
