### ISSUE TITLE
cURL error while downloading

### ISSUE THREAD

**Issue by InternetPotential29** [KevCui/animepahe-dl#68]
Hi, there is an error with cURL while downloading this anime (Isekai Maou to Shoukan Shoujo no Dorei Majutsu Ω)

![image_2022-06-19_163226908](https://user-images.githubusercontent.com/8487981/174472640-f716fc71-8dc2-4f2f-a9dd-875869ec6986.png)

**Comment by KevCui** [comment]
Hey @InternetPotential29, I tried the same command, it works for me.

The error message in the screenshot looks like curl doesn't have the permission to write output on your file system. Please try to run `curl -sSL 'https://www.github.com' -o github.html` inside the same script directory, to see if curl can create `github.html` with content.

**Comment by InternetPotential29** [comment]
No, I can still download other anime without an error. 

Here is the log file with -t option on debug.
[https://pastebin.com/Z1VVAYcf](url)

I have tried without the -t command and it works. I don't know why but on others I can do 100 threads.

**Comment by KevCui** [comment]
Hi @InternetPotential29 , thanks for the logs. The reported issue doesn't appear to be in the script itself. I guess it may be something wrong with `curl` when handling `Ω` symbol in the directory name. But I'm not able to find the exact issue in `curl` project, and I don't think I can fix that either. You could try to update `curl` to the latest version, if it helps. Otherwise, I'd suggest using normal download mode for this special case.

Let's close this issue for now since I don't think I can do any thing to fix it. If you have the same issue on other anime title, let me know, I may take another look.
