### ISSUE TITLE
Issue while downloading

### ISSUE THREAD

**Issue by CiekawyMichu** [KevCui/animepahe-dl#72]
I tried using -t to download faster, but it finishes after the first episode and it outputs a folder with segments of the video.

![obraz](https://user-images.githubusercontent.com/46295137/180760734-becd691f-4b92-49da-bac1-8465c790580f.png)

Here is the output https://pastebin.com/gKWFx40p

**Comment by KevCui** [comment]
Hey @CiekawyMichu, unfortunately the logs don't show any errors. The script appears to be finished while running the `decrypt_segments` function. So far, I don't know why, I guess maybe some segments are missing. Do you retry to download the same episode? If it's still not working, I'd suggest running the script with out the flag `-t`.

**Comment by CiekawyMichu** [comment]
I did retry a few more times, tried also other anime, nothing seems to help.

**Comment by KevCui** [comment]
Hey @CiekawyMichu, please check if running the script without `-t` works for you? If you caught any error message, let me know.

**Comment by KevCui** [comment]
Hey @CiekawyMichu, I checked again your logs. From the logs, all segments should be downloaded. I'm thinking maybe it's something wrong with bash process substitution. Could you please check which bash version on your machine? `bash --version`

**Comment by CiekawyMichu** [comment]
It's version 5.1.16(1)-release (x86_64-alpine-linux-musl)

**Comment by KevCui** [comment]
@CiekawyMichu, ok, then it shouldn't be the process substitution... Besides, the same code structure is used to download segments. As the download part works, it should work for the decrypt part as well...

I have no idea as for now what goes wrong. I removed some redundant code in the latest commit and pushed it. I don't think it can solve the issue you are facing. But maybe give it a try since I have no other idea, sorry about that.

**Comment by CiekawyMichu** [comment]
It works now, thank you very much.
