### ISSUE TITLE
EPISODES DOWNLOADED IN DUB INSTEAD OF USUAL SUB. OVERLORD II 6-13. OVERLORD III and OVERLORD IV

### ISSUE THREAD

**Issue by kraithus** [KevCui/animepahe-dl#89]
By default, the downloader would get me the subbed version of the anime. On Friday April 21st at 00:42 (CAT) I downloaded Episode 5 of Overlord II. The issue seems to be with episodes I downloaded since April 21st 4AM with 6-13 of Overlord II being in dub and the whole of Overlordd III and IV also being in dub.

I haven't tried to replicate the issue with other anime as I have very bad internet in my country. I really appreciate this project and would like to know if something on animepahe's side caused this behaviour to change or if it is only isolated to Overlord II started from episode 6 and Overlord III and IV

The command I ran to get the episodes was
`./animepahe-dl.sh -a 'Overlord' -e 6 -13 -t 4`  **for season 2**
`./animepahe-dl.sh -a 'Overlord' -e 1-13  -t 4`  **for season 3 and 4**
followed by selecting the appropriate season from the prompted screen.

**Comment by KevCui** [comment]
Hey @kraithus, by default, without any specific options, the script picks the last available resource to download. For example, https://animepahe.ru/play/2895a085-1225-9081-f6ee-f9f076fceda0/d2f4bb36725c6408a6f026f95dddb0979a2a272d75863ca73a5b9c590543f5ba, the last one is `1080p BD ENG`. That's why the dub version gets downloaded.

In this case, you can use `-o jpn` to choose sub version to download. Hope it fits your needs.

**Comment by kraithus** [comment]
That definitely fits my needs, thank you.
