### ISSUE TITLE
jq: parse error

### ISSUE THREAD

**Issue by Anas-Mughal** [KevCui/animepahe-dl#99]
./animepahe-dl.sh -a "No Game No Life!" -e  "1-90" -r  "1080" -o "jpn" -t "99999"
jq: parse error: Invalid numeric literal at line 1, column 10
[ERROR] Anime slug not found!

**Comment by KevCui** [comment]
Hey @Anas-Mughal, I don't see `[ERROR] Anime slug not found!` error when I try the same anime title. But I do see another issue and it's fixed in the last commit. Pull the latest commit and give another try? If script is still not working for you, please share some logs by running script with `-d` flag. I will take another look.

**Comment by KevCui** [comment]
I assume this reported issue is fixed? Let me close it then. Cheers.
